### ISSUE TITLE
frame: API update checklist

### ISSUE THREAD

**Issue by as** [as/frame#40]
Checklist for upcoming API update.

- [x] Write go-fix for incompatible API changes (frame)
- [x] Write go-fix for incompatible API changes (font)
- [x] Fix UTF8 support
- [x] Add tests for cached and uncached 
- [x] Remove shiny references from the API documentation
- [x] Update README.md with instructions for running `go-fix`
- [x] Update README.md with API changes and package changes
- [x] Merge flusher branch with master
- [x] Round up and close related issues resolved by this change
- [x] #37 
- [x] #25 
- [x] #21 
- [x] #17 
- [x] #3 
- [x] #2
